### PR TITLE
Render rule `guidance` as markdown in the CLI.

### LINKED ISSUE #4285: Render rule guidance as markdown in the CLI
When running `minder ruletype get`, I can see the guidance for a specific rule type.
Currently this is rendered as a simple string.
We should render it as markdown.

note: we should ensure it is sanitized before rendering

### PR DESCRIPTION
**Pull request by blkt**
# Summary

This change adds code to render the `guidance` field of a rule type definition as markdown. In case it is not possible to render it properly, it just renders the string as given.

The library used for rendering, `glamour`, internally checks for HTML tags and strips them completely from the output, ensuring safety.

Fixes #4285

## Change Type

- [ ] Bug fix (resolves an issue without affecting existing features)
- [X] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

Manual tests.

# Review Checklist:

- [X] Reviewed my own code for quality and clarity.
- [X] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [X] Checked that related changes are merged.

### CODE REVIEW

**Review by JAORMX — COMMENTED** [review]
Lovely! Can you post a sample screenshot from the rendering?

**Comment by blkt** [comment]
@JAORMX there you go!
Screenshot 2024-08-28 at 11 47 54

**Review by JAORMX — DISMISSED** [review]

**Review by eleftherias — COMMENTED** [review]
Could we add some tests for this? I know technically it is testing the external library, but it would be nice to have that verification in our codebase. Particularly when it comes to malicious content being sanitized.

**Comment by blkt** [comment]
@eleftherias I added a couple of tests, but I would say we mostly rely on the added fuzz test.
Also, I would merge this after we have decided what to do with #4304 if you're ok with it.

**Review by eleftherias — APPROVED** [review]
Thanks @blkt!
> I would merge this after we have decided what to do with https://github.com/stacklok/minder/pull/4304

Of course I'll leave it up to you when to merge, but I don't think the outcome of #4304 would impact this PR, because regardless of what input validation we do, we should still always sanitize before displaying to the user.

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
