### PR TITLE
Upgrade postgres to 16.1-alpine in docker-compose

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@JAORMX What is the version used by the production minder server?

**Comment by JAORMX** [comment]
Uhmm... I should double check

**Review by rdimitrov — APPROVED** [review]
I'll approve because I think it's worth it to try and develop locally using the latest versions of dependencies since it will allow us for a safer upgrade in staging/prod later.

**Comment by JAORMX** [comment]
I think it's fine to have latest and greatest in development. It'll be easier to know if we gotta watch out of certain things on upgrades.

**Pull request merged**
