### PR TITLE
Upgrade keycloak to 24.0

### PR DESCRIPTION
**Pull request by jhrozek**
# Summary

We've been seeing random issues with offline tokens and keycloak. Since the
new release does mention several improvements around offline tokens in release
notes, it's worth a try.

## Change Type

***Mark the type of change your PR introduces:***

- [x] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

N/A

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [ ] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by jhrozek** [comment]
Oh it's because keycloak_config errors out:
```
docker logs keycloak_config
2024-03-13 20:45:34.562  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v5.10.0 using Java 17.0.10 on 2ccd60184cbb with PID 1 (/opt/bitnami/keycloak-config-cli/keycloak-config-cli-23.0.1.jar started by ? in /opt/bitnami/keycloak-config-cli)
2024-03-13 20:45:34.563  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2024-03-13 20:45:34.866  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 0.543 seconds (JVM running for 0.772)
2024-03-13 20:45:35.350  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file 'file:/config/stacklok.yaml'
2024-03-13 20:45:35.659  WARN 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Local keycloak-config-cli (5.10.0-23.0.1) and remote Keycloak (24.0.1) may not compatible.
2024-03-13 20:45:36.409 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "maxTemporaryLockouts" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (139 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "clientOfflineSessionMaxLifespan", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "clientOfflineSessionIdleTimeout", "notBefore", "publicKey", "smtpServer", "clientPolicies", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "defaultRole", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings" [truncated]])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 1183] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["maxTemporaryLockouts"])
2024-03-13 20:45:36.409  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.161.
```

**Comment by JAORMX** [comment]
Do we need to update the keycloak config container too?

**Comment by jhrozek** [comment]
> Do we need to update the keycloak config container too?

yes!

**Comment by jhrozek** [comment]
I tested this as far as creating a new instance and minder auth login/auth whoami.

**Comment by JAORMX** [comment]
Try sneering your local account. Does that work too?

**Comment by JAORMX** [comment]
worked for me.

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
