### PR TITLE
Add watermill NATS driver

### PR DESCRIPTION
**Pull request by JAORMX**
# Summary

This adds a NATS driver for our eventer.

## Change Type

***Mark the type of change your PR introduces:***

- [ ] Bug fix (resolves an issue without affecting existing features)
- [x] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [ ] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Comment by JAORMX** [comment]
Haven't quite gotten this to work. For some reason, after very little time of running, the subscriber gets automatically closed and I haven't figured out why.

**Comment by JAORMX** [comment]
The logs look as follows:

```
{"level":"info","host":"postgres","port":5432,"user":"postgres","dbname":"minder","Timestamp":1721739573451269528,"message":"Connecting to DB"}
{"level":"info","try number":0,"Timestamp":1721739573451323076,"message":"Trying to connect to DB"}
{"level":"info","Timestamp":1721739573458164229,"message":"Connected to DB"}
{"level":"debug","component":"watermill","count":"1","Timestamp":1721739573505297867,"message":"Adding publisher decorators"}
{"level":"debug","component":"watermill","count":"1","Timestamp":1721739573505310094,"message":"Adding subscriber decorators"}
{"level":"debug","component":"watermill","count":"1","Timestamp":1721739573505330195,"message":"Adding middleware"}
{"level":"info","Timestamp":1721739573505333252,"message":"Router Metrics registered"}
{"level":"info","Timestamp":1721739573505339543,"message":"Metrics Instruments registered"}
{"level":"info","Timestamp":1721739573505341413,"message":"Using NATS driver"}
{"level":"debug","component":"watermill","count":"4","Timestamp":1721739573507646336,"message":"Adding middleware"}
{"level":"info","path":"/app/flags-config.yaml","Timestamp":1721739573507683734,"message":"Using GoFeatureFlag file provider"}
{"level":"error","exception.message":"impossible to retrieve the flags, please check your configuration: read /app/flags-config.yaml: is a directory","Timestamp":1721739573507819747,"message":"Unable to create GoFeatureFlag provider"}
{"level":"warn","Timestamp":1721739573507823563,"message":"No feature flag provider installed"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/eea.(*EEA).FlushMessageHandler-fm-flush.entity.event","topic":"flush.entity.event","Timestamp":1721739573508030579,"message":"Adding handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/engine.(*ExecutorEventHandler).HandleEntityEvent-fm-execute.entity.event","topic":"execute.entity.event","Timestamp":1721739573508054837,"message":"Adding handler"}
{"level":"debug","component":"watermill","count":"1","handlerName":"github.com/stacklok/minder/internal/engine.(*ExecutorEventHandler).HandleEntityEvent-fm-execute.entity.event","Timestamp":1721739573508061630,"message":"Adding middleware to handler"}
{"level":"debug","component":"watermill","count":"1","handlerName":"github.com/stacklok/minder/internal/engine.(*ExecutorEventHandler).HandleEntityEvent-fm-execute.entity.event","Timestamp":1721739573508065282,"message":"Adding middleware to handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/reconcilers.(*Reconciler).handleRepoReconcilerEvent-fm-internal.repo.reconciler.event","topic":"internal.repo.reconciler.event","Timestamp":1721739573508070569,"message":"Adding handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/reconcilers.(*Reconciler).handleProfileInitEvent-fm-internal.profile.init.event","topic":"internal.profile.init.event","Timestamp":1721739573508075231,"message":"Adding handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/reconcilers.(*Reconciler).handleEntityDeleteEvent-fm-internal.entity.delete.event","topic":"internal.entity.delete.event","Timestamp":1721739573508080125,"message":"Adding handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/reconcilers.(*Reconciler).handleEntityAddEvent-fm-internal.entity.add.event","topic":"internal.entity.add.event","Timestamp":1721739573508084725,"message":"Adding handler"}
{"level":"info","component":"watermill","topic":"internal.provider.installation.removed.event","handler_name":"github.com/stacklok/minder/internal/providers/github/installations.(*InstallationManager).handleProviderInstallationEvent-fm-internal.provider.installation.removed.event","Timestamp":1721739573508090493,"message":"Adding handler"}
{"level":"info","component":"watermill","handler_name":"github.com/stacklok/minder/internal/email/noop.(*noop).Register.func1-invite.email.event","topic":"invite.email.event","Timestamp":1721739573508120621,"message":"Adding handler"}
{"level":"debug","component":"watermill","Timestamp":1721739573508137730,"message":"Loading plugins"}
{"level":"info","component":"watermill","count":8,"Timestamp":1721739573508156087,"message":"Running router handlers"}
{"level":"debug","component":"watermill","topic":"internal.provider.installation.removed.event","subscriber_name":"github.com/stacklok/minder/internal/providers/github/installations.(*InstallationManager).handleProviderInstallationEvent-fm-internal.provider.installation.removed.event","Timestamp":1721739573508401359,"message":"Subscribing to topic"}
{"level":"debug","component":"watermill","subscriber_num":0,"topic":"internal.provider.installation.removed.event","Timestamp":1721739573508417754,"message":"Starting subscriber"}
{"level":"debug","component":"watermill","Timestamp":1721739573508827360,"message":"Closing subscriber"}
{"level":"debug","Timestamp":1721739573509543069,"message":"Starting gRPC server on 0.0.0.0:8090"}
{"level":"debug","Timestamp":1721739573510147771,"message":"Starting HTTP server on 0.0.0.0:8080"}
{"level":"debug","Timestamp":1721739573510558482,"message":"Starting metrics server on 0.0.0.0:9090"}
{"level":"info","component":"watermill","Timestamp":1721739603509350388,"message":"Subscriber closed"}
{"level":"info","component":"watermill","Timestamp":1721739603509368485,"message":"Closing router"}
{"level":"info","component":"watermill","Timestamp":1721739613510476128,"message":"Router closed"}
{"level":"debug","Timestamp":1721739613510753746,"message":"shutting down 'Metric server'"}
{"level":"debug","Timestamp":1721739613510892697,"message":"shutting down 'HTTP server'"}
{"level":"debug","Timestamp":1721739613510895606,"message":"shutting down 'MeterProvider'"}
{"level":"debug","Timestamp":1721739613510956352,"message":"shutting down 'GRPC server'"}
```

**Review by jhrozek — COMMENTED** [review]
Except for the linter issue, this seems easy enough code to read.
Is the NATS back end being maintained?

**Comment by JAORMX** [comment]
> Is the NATS back end being maintained?

@jhrozek somewhat. Just making the migration to NATS in steps with this. I think after this I would just start re-implementing the eventer to have a full blown NATS driver... If I get this to work. Although, I haven't really put much time in debugging the issue.

**Pull request closed without merging**
