### PR TITLE
Add additional test coverage for common functions in GitHub provider

### LINKED ISSUE #4380: Improve test coverage in parts of Minder with low coverage.
Certain parts of Minder have low unit test coverage. In at least one recent incident, the incident could have been prevented if there had been some unit test coverage of the codepath in question (there was none).

Based on some recent pain points, and looking at stats from Coveralls, some of the files we should focus attention our attention on are:

1. [internal/providers/github/common.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fproviders%2Fgithub%2Fcommon.go)
2. [internal/controlplane/handlers_profile.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_profile.go)
3. [internal/controlplane/handlers_evalstatus.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_evalstatus.go)
4. [internal/verifier/sigstore/container/container.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fverifier%2Fsigstore%2Fcontainer%2Fcontainer.go)
5. [internal/util/helpers.go](https://coveralls.io/builds/69632370/source?filename=internal%2Futil%2Fhelpers.go)
6. [internal/controlplane/handlers_projects.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_projects.go)
7. [internal/controlplane/handlers_user.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_user.go)
8. [internal/controlplane/handlers_oauth.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_oauth.go)
9. [...tions/alert/security_advisory/security_advisory.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fengine%2Factions%2Falert%2Fsecurity_advisory%2Fsecurity_advisory.go)
10. [internal/controlplane/handlers_artifacts.go](https://coveralls.io/builds/69632370/source?filename=internal%2Fcontrolplane%2Fhandlers_artifacts.go)

### PR DESCRIPTION
**Pull request by gajananan**
# Summary

Currently common functions in GitHub provider lacks test coverage when converting github repos to minder repos.
This commit adds test coverage for ConvertRepositories for github.

Ref #4380 

## Change Type

***Mark the type of change your PR introduces:***

- [ ] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [x] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [x] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [x] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Review by eleftherias — COMMENTED** [review]
Thanks for the PR @gajananan!

The code changes look good, there are just a few cleanup items we need before merging this.
Could you run `make lint` on you local machine before committing? This will show the lint errors.
Could you change the PR description from `Fixes #4380` to `Ref #4380`? If we have the `Fixes` keyword then it will close the associated issue, which we don't want in this case.

**Comment by gajananan** [comment]
> Thanks for the PR @gajananan!
> 
> The code changes look good, there are just a few cleanup items we need before merging this. Could you run `make lint` on you local machine before committing? This will show the lint errors. Could you change the PR description from `Fixes #4380` to `Ref #4380`? If we have the `Fixes` keyword then it will close the associated issue, which we don't want in this case.

Thank you.  @eleftherias. I managed fix the lint config on my machine and run the `make lint` properly.  it looks fine now.

**Comment by eleftherias** [comment]
> > Thanks for the PR @gajananan!
> > The code changes look good, there are just a few cleanup items we need before merging this. Could you run `make lint` on you local machine before committing? This will show the lint errors. Could you change the PR description from `Fixes #4380` to `Ref #4380`? If we have the `Fixes` keyword then it will close the associated issue, which we don't want in this case.
> 
> Thank you. @eleftherias. I managed fix the lint config on my machine and run the `make lint` properly. it looks fine locally (no lint errors) in my machine now. However, lint seems to be failing in CI.

It could be a mismatched version of the lint tool. Could you try running `make bootstrap` (to install the required version) and then `make lint` again?

**Comment by gajananan** [comment]
> > > Thanks for the PR @gajananan!
> > > The code changes look good, there are just a few cleanup items we need before merging this. Could you run `make lint` on you local machine before committing? This will show the lint errors. Could you change the PR description from `Fixes #4380` to `Ref #4380`? If we have the `Fixes` keyword then it will close the associated issue, which we don't want in this case.
> > 
> > 
> > Thank you. @eleftherias. I managed fix the lint config on my machine and run the `make lint` properly. it looks fine locally (no lint errors) in my machine now. However, lint seems to be failing in CI.
> 
> It could be a mismatched version of the lint tool. Could you try running `make bootstrap` (to install the required version) and then `make lint` again?

Thank you, @eleftherias. I was not aware I was using an old version of lint.  It is now fixed.

**Review by eleftherias — APPROVED** [review]
Thanks for your contribution @gajananan!

**Pull request merged**
