### PR TITLE
Artifacts: Properly handle untagged images

### LINKED ISSUE #3225: Artifact: Ingesting images by digest always returns "latest"
### Describe the issue

When ingesting a container image by digest and no tags are defined, the ingester will skip the specified digest and ingest the last image returned by the the API (generally matching `latest`)

### To Reproduce

This entity should ingest `e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181` but instead ingests `4a80bffe07d74bece13c3b954c6463aa25b36492bdfcfc0f674381e0b43f58c9` (`latest` at the time of this report)

```yaml
---
owner: jakubtestorg
name: good-repo-go
type: container
versions: 
  - sha: sha256:e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181
  - tags: []
```

### What version are you using?

900bb165611a1b04ab769255ca7f2719fb2b268b

### PR DESCRIPTION
**Pull request by puerco**
# Summary

This PR fixes the `artifact.isSkippable` function to properly handle the ingestion of untagged images. It also adds a test to ensure it behaves as expected.

It also optimizes the selection of images to drop early any artifact candidates when hashes don't match, improving the performance of the filtering process considerably.

Fixes #3225

## Change Type

***Mark the type of change your PR introduces:***

- [x] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [x] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [x] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [x] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Review by dmjb — APPROVED** [review]

**Comment by jhrozek** [comment]
Actually, let's not push this just yet, I think there might be a bug. I was seeing some weird behaviour with this branch which went away once I switched to main.

**Comment by puerco** [comment]
Let me know which weird behavior and I can check it

**Comment by jhrozek** [comment]
> Let me know which weird behavior and I can check it

OK, I know what happened, but I don't have a good answer on fixing it. So there's two ways we can ingest an artifact:
1) "directly", through either a webhook or the mindev command. This does pass on the Version, typically the one you ingest.
2) through a reconcile. This is normally used when you first create a profile and then you register the repo. The code is [here](https://github.com/stacklok/minder/blob/7fc9740fa5735c4707eaeed297ece69971c481a0/internal/reconcilers/repository.go#L183). In this case we send a nil Versions which means that the loop iterates over slice with len == which means the default matches=false is used.

Would it be reasonable to adjust the new code to only execute on len(artifact.Versions) > 0 ?

**Comment by JAORMX** [comment]
> 2\. through a reconcile. This is normally used when you first create a profile and then you register the repo. The code is [here](https://github.com/stacklok/minder/blob/7fc9740fa5735c4707eaeed297ece69971c481a0/internal/reconcilers/repository.go#L183). In this case we send a nil Versions which means that the loop iterates over slice with len == which means the default matches=false is used.

I actually think the reconcile should be the one to iterate through the versions and pass a single event per version it reconciles. That way it's the same behavior as the webhook and we don't need to special case this. It also makes the artifact ingest logic simpler.

**Comment by jhrozek** [comment]
> > 2. through a reconcile. This is normally used when you first create a profile and then you register the repo. The code is [here](https://github.com/stacklok/minder/blob/7fc9740fa5735c4707eaeed297ece69971c481a0/internal/reconcilers/repository.go#L183). In this case we send a nil Versions which means that the loop iterates over slice with len == which means the default matches=false is used.
> 
> I actually think the reconcile should be the one to iterate through the versions and pass a single event per version it reconciles. That way it's the same behavior as the webhook and we don't need to special case this. It also makes the artifact ingest logic simpler.

This would be a LOT of versions and events, most of which would be thrown away.

**Comment by JAORMX** [comment]
> This would be a LOT of versions and events, most of which would be thrown away.

uhm... why not just try to get the status of the `latest` tag? Do we really want to iterate over everything? Trying to think of use-cases.

**Comment by jhrozek** [comment]
> > This would be a LOT of versions and events, most of which would be thrown away.
> 
> uhm... why not just try to get the status of the `latest` tag? Do we really want to iterate over everything? Trying to think of use-cases.

I'm not sure I understand what the proposal is but IIRC the GH API didn't let you iterate over tags, you had to list everything and then filter yourself. Maybe this is different with the OCI API?

**Comment by JAORMX** [comment]
> > > This would be a LOT of versions and events, most of which would be thrown away.
> > 
> > 
> > uhm... why not just try to get the status of the `latest` tag? Do we really want to iterate over everything? Trying to think of use-cases.
> 
> I'm not sure I understand what the proposal is but IIRC the GH API didn't let you iterate over tags, you had to list everything and then filter yourself. Maybe this is different with the OCI API?

yeah, there are query parameters that allow you to order by creation date and limit the number of responses.

**Comment by rdimitrov** [comment]
I remember we were unsure of the practicality of having untagged images along with some implementation details that made us discard them.

Let's wait merging this for a bit until we meet to chat more about it.

**Pull request closed without merging**
