### PR TITLE
Actions: Complete version tags in workflow comments 

### LINKED ISSUE #2300: Switch away from actions using a deprecated nodejs version
There are warnings that we are using actions that use a deprecated NodeJS version.

**Details:**
- [x] [lint / Go Lint](https://github.com/stacklok/minder/actions/runs/7818466077/job/21329022693)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- [x] [image-build / Build Helm chart](https://github.com/stacklok/minder/actions/runs/7818466077/job/21329024441)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- [x] [test / Unit testing](https://github.com/stacklok/minder/actions/runs/7818466077/job/21329023172)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by puerco**
# Summary

This pr adds the complete version tags in our workflows and bumps two action version which were stuck pinned to commits in branches.

While fixing https://github.com/stacklok/minder/issues/2300 I noticed that the versions in the workflow tags in our workflows are not complete and this is preventing dependabot from updating them when bumping versions. This makes it hard to know  which revisions we're running.

Fixes #2300

## Change Type

- [ ] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [x] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [ ] Reviewed my own code for quality and clarity.
- [ ] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Comment by evankanderson** [comment]
> While fixing #2300 I noticed that the versions in the workflow tags in our workflows are not complete and this is preventing dependabot from updating them when bumping versions. This makes it hard to know which revisions we're running.

Is this pinning something we did with https://github.com/stacklok/frizbee?  If so, we might need to modify that, as well.

**Review by evankanderson — APPROVED** [review]

**Comment by puerco** [comment]
@evankanderson ah let me merge this and I'll running it and see what happens

**Comment by puerco** [comment]
I ran frizbee it and worked perfectly, It caught one that was referenced with a tag and I missed ( https://github.com/stacklok/minder/pull/2975 )

**Comment by evankanderson** [comment]
We should have a frizbee rule remediating on Minder.  We should figure out why that didn't fire on Monday.

**Pull request merged**
