### PR TITLE
WIP: Pass ingest result to remediator

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by rdimitrov** [comment]
Why do we want to pass the ingest result to actions? I like having the linear chain of events - ingesting -> eval -> actions, so actions continue to respond based on the eval result and the eval result is based on the ingest result.

**Comment by JAORMX** [comment]
> Why do we want to pass the ingest result to actions? I like having the linear chain of events - ingesting -> eval -> actions, so actions continue to respond based on the eval result and the eval result is based on the ingest result.

this is a WIP PR. But the idea is to be able to do remediations based on the contents of what was ingested. e.g. being able to do changes to the git tree that was ingested to form PRs.

**Comment by JAORMX** [comment]
This doesn't break the linearity at all

**Comment by rdimitrov** [comment]
> > Why do we want to pass the ingest result to actions? I like having the linear chain of events - ingesting -> eval -> actions, so actions continue to respond based on the eval result and the eval result is based on the ingest result.
> 
> this is a WIP PR. But the idea is to be able to do remediations based on the contents of what was ingested. e.g. being able to do changes to the git tree that was ingested to form PRs.

Ah, I see 👍 I guess it fits better to the `ActionsParams` interface then instead of updating the Actions interface?

**Comment by JAORMX** [comment]
I can try that

**Pull request closed without merging**
