### PR TITLE
Warn users when the target environment for the CLI is staging

### PR DESCRIPTION
**Pull request by AGMETEOR**
Staging can sometimes be unstable and there's need to warn users about this

### CODE REVIEW

**Comment by JAORMX** [comment]
Thanks for working on this! It LGTM. Just the CLA is missing and we're good to go.

**Comment by AGMETEOR** [comment]
> Thanks for working on this! It LGTM. Just the CLA is missing and we're good to go.

I just signed it. I wonder why it's check is not passing. Do I need to modify my commit messages?

**Comment by JAORMX** [comment]
@dussab any idea what's missing on the CLA side?

**Comment by dussab** [comment]
@AGMETEOR Thanks for the contribution! Is the email that you used for your commit added to your GitHub account? 

Reference: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by evankanderson** [comment]
(Note that GitHub's UI tends to obscure the actual email in the commits)

It looks like your commits are using `allan@Allans-MBP.domain.name`, so you may need to configure Git with a proper email address for commits and then rewrite the author history for those 4 commits.

**Comment by AGMETEOR** [comment]
Closing in favor of https://github.com/stacklok/minder/pull/2071

**Pull request closed without merging**
