### PR TITLE
docs: fixes broken link to CLI docs on the readme

### PR DESCRIPTION
**Pull request by andresgalante**
There is a broken link on the read me. This PR is fixing it :)

### CODE REVIEW

**Comment by JAORMX** [comment]
Thanks a lot for the contribution! Once CI is happy and the CLA is signed, we'll get this merged.

**Comment by andresgalante** [comment]
Actually, should it be linked to here instead: https://minder-docs.stacklok.dev/ref/api ?

**Review by JAORMX — APPROVED** [review]

**Comment by JAORMX** [comment]
> Actually, should it be linked to here instead: https://minder-docs.stacklok.dev/ref/api ?

I think the ref you linked it to is just fine. Though it would be handy to also have a reference to the API handy.

**Comment by andresgalante** [comment]
I agree, since I have it open let me add a reference to the API too

**Pull request merged**
