### PR TITLE
Don't execute actions when running `mindev ruletype test`

### PR DESCRIPTION
**Pull request by JAORMX**
This overwrites the remediation and alert to be `off` since we don't want to
execute actions when testing. This is not _yet_ supported and causes a segfault.

So, let's turn it off for now. If the need comes to test the actions themselves
with `mindev` we can work on turning it on later. But, for now, no segfault
is better.

Closes: https://github.com/stacklok/minder/issues/1858

### CODE REVIEW

**Comment by jhrozek** [comment]
Do we need to disable remediation too? I use that for testing ...

**Comment by JAORMX** [comment]
@jhrozek does it work? I thought it segfaulted too.

**Comment by jhrozek** [comment]
Yes I use that all the time

**Comment by JAORMX** [comment]
So it's only alerts. Got it.

**Comment by JAORMX** [comment]
@jhrozek fixed.

**Review by jhrozek — APPROVED** [review]

**Pull request merged**
